# Generated by Django 5.2.8 on 2025-11-09 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_matkul_diajar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nilai',
            name='mahasiswa',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
